version: "3.8"

services:
  nextjs-app:
    image: node:18-alpine
    container_name: nextjs-container
    working_dir: /app
    ports:
      - "3000:3000" # Expose port 3000 for the Next.js app
    volumes:
      - .:/app
      - /app/node_modules
    command: >
      sh -c "npm install
      && npm run dev"
