#controllers:
#    resource:
#        path: ../src/Controller/
#        namespace: App\Controller
#    type: attribute
#
#auth:
#    path: /api/auth
#    methods: ['POST']
#    
#api_login_check:
#    path: /api/login_check


controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

auth:
    path: /api/auth
    methods: ["POST"]
