name: Build and Push to Artifact Registry

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

env:
  PROJECT_ID: avian-sunlight-410710
  REGION: europe-west10
  GAR_LOCATION: europe-west10-docker.pkg.dev/avian-sunlight-410710/chirp-repo/

jobs:
  build-push-artifact:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
        
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.SERVICE_ACCOUNT_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build image
        run: docker build . --file Dockerfile --tag ${{ env.GAR_LOCATION }}chirp-image:latest
        # working-directory: qwerty084/lf8

      - name: Push image
        run: docker push ${{ env.GAR_LOCATION }}chirp-image:latest
