name: Google Cloud Deploy
on:
    release:
      types: [published]

    workflow_dispatch:

jobs:
  build-push-gcr:
    name: Deploy
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./api

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Gcloud CLI
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${ secrets.GOOGLE_PROJECT }}
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        export_default_credentials: true

    - name: Build and Push Docker Image
      env: 
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      run: |
        gcloud auth configure-docker europe-west10-docker.pkg.dev
        docker build -t europe-west10-docker.pkg.dev/avian-sunlight-410710/chirp-repo/chirp:latest ./api
        docker push europe-west10-docker.pkg.dev/avian-sunlight-410710/chirp-repo/chirp:latest
