name: Docker Test

on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:

  build-container:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag frankenphp-composer:$(date +%s)
